python3 main.py \
	--func_name "extended_rosenbrock" \
	--stepsize_method "simple" \
	--criterion_method "armijo" \
	--opt_method "sr1" \
	--max_iters 1e3 \
	--rho 1e-4 \
	--sigma 0.9 \
	--eps 1e-8 \
	--m 4 \
	--beta 1.1